before_script:
  # - apt-get update && apt-get install -y -qq python3 python3-pip
  - echo "Python version is $(python -V)"
  - pip install -r hypomeals/requirements.txt

lint:
  script:
    - prospector --profile prospector_profile.yml

test:
  script:
    - python hypomeals/manage.py test meals