before_script:
  - echo "Python version is $(python -V)"
  - pip install -r hypomeals/requirements.txt

lint:
  script:
    - prospector --profile .prospector.yaml

test:
  script:
    - python hypomeals/manage.py test meals