output-format: json

strictness: medium
test-warnings: true
doc-warnings: false

ignore-paths:
  - hypomeals/meals/migrations

pep8:
  options:
    max-line-length: 88

pylint:
  disable:
    - logging-fstring-interpolation
    - too-many-arguments
    - too-many-locals
    - no-value-for-parameter

mccabe:
  run: false

dodgy:
  run: false