version: '3'

services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: "Hyp0Mea1sR0cks!"
        volumes:
            - ./data:/var/lib/postgresql/data
    web-init:
        build: ./hypomeals
        command: /code/initserver.sh
        user: nobody
        environment:
            - "DJANGO_DB_HOST=db"
            - "DJANGO_DB_PORT=5432"
        volumes:
            - ./hypomeals:/code
    web:
        build: ./hypomeals
        user: nobody
        environment:
            - "DJANGO_DB_HOST=db"
            - "DJANGO_DB_PORT=5432"
        command: /code/runserver.sh
        volumes:
            - ./hypomeals:/code
        expose:
            - "8000"
        depends_on:
            - web-init
            - db
    nginx:
        image: nginx:latest
        ports:
            - "443:443"
        volumes:
            - ./nginx/config:/etc/nginx/conf.d
            - ./nginx/certs:/etc/nginx/certs
        depends_on:
            - web
