version: '3'

services:
    db:
        build: ./postgres
        environment:
            POSTGRES_PASSWORD: "Hyp0Mea1sR0cks!"
        restart: always
        volumes:
            - db-data:/var/lib/postgresql/data
            - ./credentials/vcm-4081.vm.duke.edu.pem:/var/lib/postgresql/certs/server.crt:ro
            - ./credentials/vcm-4081.vm.duke.edu.key:/var/lib/postgresql/certs/server.key:ro
    web-init:
        build: ./hypomeals
        command: /code/initserver.sh
        user: nobody
        env_file:
            - web-vars-prod.env
        volumes:
            - ./hypomeals/logs:/code/logs
            - ./static:/srv/static
    redis:
        image: "redis:5.0.3"
        volumes:
            - ./hypomeals/logs:/var/log/redis
        #     - ./redis/data:/data
        expose:
            - "6379"
    web:
        build: ./hypomeals
        user: nobody
        env_file:
            - web-vars-prod.env
        command: /code/runserver.sh
        volumes:
            - ./hypomeals/logs:/code/logs
            - ./credentials/hypomeals-write-only.json:/code/hypomeals-write-only.json:ro
            - ./credentials/oauth_config.json:/code/oauth_config.json:ro
        expose:
            - "8000"
        depends_on:
            - celery
            - celery-beat
    celery:
        build: ./hypomeals
        user: nobody
        env_file:
            - web-vars-prod.env
        environment:
            - DJANGO_EMAIL_USER=${DJANGO_EMAIL_USER}
            - DJANGO_EMAIL_FROM=${DJANGO_EMAIL_FROM}
            - DJANGO_EMAIL_PASSWORD=${DJANGO_EMAIL_PASSWORD}
        command: /code/runcelery.sh
        volumes:
            - ./hypomeals/logs:/code/logs
            - ./credentials/backup.key:/code/backup.key:ro
            - ./credentials/hypomeals-write-only.json:/code/hypomeals-write-only.json:ro
        depends_on:
            - redis
    celery-beat:
        build: ./hypomeals
        user: nobody
        env_file:
            - web-vars-prod.env
        command: /code/runcelerybeat.sh
        volumes:
            - ./hypomeals/logs:/code/logs
        depends_on:
            - redis
            - celery
    nginx:
        image: nginx:latest
        ports:
            - "443:443"
        volumes:
            - ./nginx/config:/etc/nginx/conf.d
            - ./credentials:/etc/nginx/certs:ro
            - ./static:/srv/static/
            - ./hypomeals/logs/:/var/log/nginx/
        depends_on:
            - web
volumes:
    db-data:
