version: '3'

services:
    # We will be using a remote DB
    # db:
    #     image: postgres
    #     environment:
    #         POSTGRES_PASSWORD: ""
    #     volumes:
    #         - data-volume:/var/lib/postgresql/data
    #     ports:
    #         - 5432:5432
    web-init:
        build: ./hypomeals
        command: /code/initserver.sh
        volumes:
            - ./hypomeals:/code
    web:
        build: ./hypomeals
        user: nobody
        command: /code/runserver.sh
        volumes:
            - ./hypomeals:/code
        expose:
            - "8000"
        depends_on:
            - web-init
    nginx:
        image: nginx:latest
        ports:
            - "443:443"
        volumes:
            - ./nginx/config:/etc/nginx/conf.d
            - ./nginx/certs:/etc/nginx/certs
        depends_on:
            - web
volumes:
   data-volume:
