version: '3'

services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: "Hyp0Mea1sR0cks!"
        ports:
            - "5432:5432"
        restart: always
        volumes:
            - db-data:/var/lib/postgresql/data
    web-init:
        build: ./hypomeals
        command: /code/initserver.sh
        user: nobody
        environment:
            - "DJANGO_SETTINGS_MODULE=HypoMeals.settings_prod"
            - "DJANGO_DB_HOST=db"
            - "DJANGO_DB_PORT=5432"
            - "CELERY_REDIS_HOST=redis"
            - "CELERY_REDIS_PORT=6379"
        volumes:
            - ./hypomeals:/code
            - ./static:/srv/static
    redis:
        image: "redis:5.0.3"
        # volumes:
        #     - ./redis/data:/data
        expose:
            - "6379"
    web:
        build: ./hypomeals
        user: nobody
        environment:
            - "DJANGO_SETTINGS_MODULE=HypoMeals.settings_prod"
            - "DJANGO_DB_HOST=db"
            - "DJANGO_DB_PORT=5432"
            - "CELERY_REDIS_HOST=redis"
            - "CELERY_REDIS_PORT=6379"
        command: /code/runserver.sh
        volumes:
            - ./hypomeals:/code
            - ./static:/srv/static
        expose:
            - "8000"
        depends_on:
            - celery
    celery:
        build: ./hypomeals
        user: nobody
        environment:
            - "DJANGO_SETTINGS_MODULE=HypoMeals.settings_prod"
            - "DJANGO_DB_HOST=db"
            - "DJANGO_DB_PORT=5432"
            - "CELERY_REDIS_HOST=redis"
            - "CELERY_REDIS_PORT=6379"
        command: /code/runcelery.sh
        volumes:
            - ./hypomeals:/code
        depends_on:
            - redis
    nginx:
        image: nginx:latest
        ports:
            - "443:443"
        volumes:
            - ./nginx/config:/etc/nginx/conf.d
            - ./nginx/certs:/etc/nginx/certs
            - ./static:/srv/static/
            - ./hypomeals/logs/:/var/log/nginx/
        depends_on:
            - web

volumes:
    db-data: