version: '3'

services:
    # We are using a remote DB
    # db:
    #     image: postgres
    #     environment:
    #         POSTGRES_PASSWORD: "Hyp0Mea1sR0cks!"
    #     volumes:
    #         - ./data:/var/lib/postgresql/data
    web-init:
        build: ./hypomeals
        command: /code/initserver.sh
        user: nobody
        environment:
            - "DJANGO_DB_HOST=db"
            - "DJANGO_DB_PORT=5555"
        volumes:
            - ./hypomeals:/code
            - ./static:/srv/static
    web:
        build: ./hypomeals
        user: nobody
        environment:
            - "DJANGO_DB_HOST=db"
            - "DJANGO_DB_PORT=5555"
        command: /code/runserver.sh
        volumes:
            - ./hypomeals:/code
            - ./static:/srv/static
        expose:
            - "8000"
        depends_on:
            - web-init
            - db
    nginx:
        image: nginx:latest
        ports:
            - "443:443"
        volumes:
            - ./nginx/config:/etc/nginx/conf.d
            - ./nginx/certs:/etc/nginx/certs
            - ./static:/srv/static/
            - ./hypomeals/logs/:/var/log/nginx/
        depends_on:
            - web
