# WARNING: This docker-compose file contains several settings
# that might make the resulting containers unsafe or insecure.
# Use of this file in a production environment is not advised.
# Use the "docker-compose-prod.yml" version instead.

version: '3'

services:
    db:
        build: ./postgres
        environment:
            POSTGRES_PASSWORD: "Hyp0Mea1sR0cks!"
        restart: always
        volumes:
            - db-data:/var/lib/postgresql/data
            - ./credentials/vcm-4081.vm.duke.edu.pem:/var/lib/postgresql/certs/server.crt:ro
            - ./credentials/vcm-4081.vm.duke.edu.key:/var/lib/postgresql/certs/server.key:ro
        ports:
            - "5432:5432"
    web-init:
        build: ./hypomeals
        command: /code/initserver.sh
        user: nobody
        env_file:
            - web-vars.env
        volumes:
            - ./hypomeals:/code
            - ./static:/srv/static
    redis:
        image: "redis:5.0.3"
        volumes:
            - ./hypomeals/logs:/var/log/redis
        #     - ./redis/data:/data
        expose:
            - "6379"
        ports:
            - "6379:6379"
    web:
        build: ./hypomeals
        user: nobody
        env_file:
            - web-vars.env
        command: /code/runserver.sh
        volumes:
            - ./hypomeals:/code
            - ./static:/srv/static
            - ./credentials/hypomeals-write-only.json:/code/hypomeals-write-only.json:ro
            - ./credentials/oauth_config.json:/code/oauth_config.json:ro
        expose:
            - "8000"
        depends_on:
            - celery
            - celery-beat
    celery:
        build: ./hypomeals
        user: nobody
        env_file:
            - web-vars.env
        command: /code/runcelery.sh
        volumes:
            - ./hypomeals:/code
            - ./credentials/backup.key:/code/backup.key:ro
            - ./credentials/hypomeals-write-only.json:/code/hypomeals-write-only.json:ro
            - ./credentials/email_config.json:/code/email_config.json:ro
        depends_on:
            - redis
    # This is a scheduler service that runs the daily jobs
    celery-beat:
        build: ./hypomeals
        user: nobody
        env_file:
            - web-vars.env
        command: /code/runcelerybeat.sh
        volumes:
            - ./hypomeals:/code
        depends_on:
            - redis
            - celery
    nginx:
        image: nginx:latest
        ports:
            - "443:443"
        volumes:
            - ./nginx/config:/etc/nginx/conf.d
            - ./credentials:/etc/nginx/certs:ro
            - ./static:/srv/static/
            - ./hypomeals/logs/:/var/log/nginx/
        depends_on:
            - web
volumes:
    db-data:
