# Generated by Django 2.1.5 on 2019-01-17 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('name', models.CharField(max_length=100, unique=True)),
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=100)),
                ('cost', models.FloatField()),
                ('comment', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('name', models.CharField(max_length=32, unique=True)),
                ('number', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='SKU Number')),
                ('unit_size', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SkuIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('ingredient_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.Ingredient')),
                ('sku_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.Sku')),
            ],
        ),
        migrations.CreateModel(
            name='Upc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc_number', models.CharField(max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='sku',
            name='case_upc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='meals.Upc'),
        ),
        migrations.AddField(
            model_name='sku',
            name='ingredients',
            field=models.ManyToManyField(through='meals.SkuIngredient', to='meals.Ingredient'),
        ),
        migrations.AddField(
            model_name='sku',
            name='product_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.ProductLine'),
        ),
        migrations.AddField(
            model_name='sku',
            name='unit_upc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='meals.Upc'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.Vendor'),
        ),
        migrations.AlterUniqueTogether(
            name='skuingredient',
            unique_together={('sku_number', 'ingredient_number')},
        ),
    ]
