# Generated by Django 2.1.5 on 2019-02-13 06:35

from django.db import migrations

from meals.constants import UNITS


def add_units(apps, schema_editor):
    Unit = apps.get_model("meals", "Unit")
    all_units = []
    for unit_type, units in UNITS.items():
        for symbol, options in units.items():
            all_units.append(Unit(symbol=symbol, unit_type=unit_type, **options))
    Unit.objects.bulk_create(all_units)


class Migration(migrations.Migration):

    dependencies = [("meals", "0002_auto_20190213_0744")]

    operations = [migrations.RunPython(add_units)]