# Generated by Django 2.1.5 on 2019-01-22 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_auto_20190117_0407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='productline',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='sku',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='upc',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['pk']},
        ),
    ]
