# Generated by Django 2.1.5 on 2019-01-21 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_profile_profileinterest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufactureDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='profileinterest',
            name='profile',
        ),
        migrations.RenameModel(
            old_name='Profile',
            new_name='ManufactureGoal',
        ),
        migrations.DeleteModel(
            name='ProfileInterest',
        ),
        migrations.AddField(
            model_name='manufacturedetail',
            name='form_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.ManufactureGoal'),
        ),
    ]
