# Generated by Django 2.1.7 on 2019-02-17 23:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_auto_20190213_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaingredient',
            name='formula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.Formula', verbose_name='Formula#'),
        ),
        migrations.AlterField(
            model_name='formulaingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='size',
            field=models.DecimalField(decimal_places=6, max_digits=12, validators=[django.core.validators.MinValueValidator(limit_value=1e-06, message='Size of ingredient must be positive.')], verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='scale_factor',
            field=models.DecimalField(decimal_places=6, max_digits=12, validators=[django.core.validators.MinValueValidator(limit_value=1e-06, message='Formula scale factor must be positive.')]),
        ),
    ]
