# Generated by Django 2.1.5 on 2019-01-27 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_auto_20190122_0225'),
        ('meals', '0004_auto_20190121_1316'),
    ]

    operations = [
    ]
