# Generated by Django 2.1.7 on 2019-02-22 03:01

from django.db import migrations, models
import django.db.models.deletion
import meals.utils


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_auto_20190217_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Start time')),
                ('goal_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='meals.GoalItem')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled', to='meals.ManufacturingLine')),
            ],
            bases=(models.Model, meals.utils.ModelFieldsCompareMixin, meals.utils.AttributeResolutionMixin),
        ),
        migrations.RemoveField(
            model_name='goal',
            name='file',
        ),
        migrations.AddField(
            model_name='goal',
            name='is_enabled',
            field=models.BooleanField(default=False, verbose_name='Enabled'),
        ),
        migrations.AlterUniqueTogether(
            name='goalschedule',
            unique_together={('goal_item', 'line')},
        ),
    ]
