# Generated by Django 2.1.7 on 2019-02-22 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_auto_20190222_0301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skumanufacturingline',
            old_name='manufacturing_line',
            new_name='line',
        ),
        migrations.AlterField(
            model_name='skumanufacturingline',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='line', to='meals.Sku'),
        ),
        migrations.AlterUniqueTogether(
            name='skumanufacturingline',
            unique_together={('sku', 'line')},
        ),
    ]
