# Generated by Django 2.1.7 on 2019-02-26 05:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_auto_20190222_0315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skumanufacturingline',
            name='rate',
        ),
        migrations.AddField(
            model_name='goalschedule',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End time'),
        ),
        migrations.AddField(
            model_name='sku',
            name='manufacturing_rate',
            field=models.DecimalField(decimal_places=6, default=1.0, help_text='Manufacturing rate for this SKU in cases per hour', max_digits=12, validators=[django.core.validators.MinValueValidator(limit_value=1e-06, message='The manufacturing rate must be positive.')], verbose_name='Manufacturing Rate'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(limit_value=0.01, message='Cost must be positive.')], verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='scale_factor',
            field=models.DecimalField(decimal_places=6, max_digits=12, validators=[django.core.validators.MinValueValidator(limit_value=1e-06, message='Unit scale factor must be positive.')]),
        ),
    ]
