# Generated by Django 2.1.5 on 2019-01-28 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0008_auto_20190128_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='case_upc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='meals.Upc'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
