# Generated by Django 2.1.7 on 2019-02-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0009_auto_20190227_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Name'),
        ),
    ]
