# Generated by Django 2.1.5 on 2019-01-30 21:14

from django.db import migrations, models
import meals.utils


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0009_auto_20190128_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturegoal',
            name='file',
            field=models.FileField(default='manufacture_goal/', upload_to=meals.utils.UploadToPathAndRename('pk', 'manufacture_goal/')),
        ),
    ]
