# Generated by Django 2.1.5 on 2019-02-03 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0010_manufacturegoal_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='case_upc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='meals.Upc', verbose_name='Case UPC#'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='count',
            field=models.IntegerField(help_text='Number of units per case', verbose_name='Count per case'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='ingredients',
            field=models.ManyToManyField(through='meals.SkuIngredient', to='meals.Ingredient', verbose_name='Ingredients'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='SKU#'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='product_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.ProductLine', verbose_name='Product Line'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='unit_upc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='meals.Upc', verbose_name='Unit UPC#'),
        ),
    ]
