# Generated by Django 2.1.7 on 2019-03-04 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0010_auto_20190227_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalschedule',
            name='override_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='manufacturingline',
            name='skus',
            field=models.ManyToManyField(through='meals.SkuManufacturingLine', to='meals.Sku', verbose_name='SKUs'),
        ),
        migrations.AlterField(
            model_name='formulaingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.Ingredient', verbose_name='Ingr#'),
        ),
        migrations.AlterField(
            model_name='skumanufacturingline',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.ManufacturingLine'),
        ),
        migrations.AlterField(
            model_name='skumanufacturingline',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.Sku'),
        ),
    ]
