# Generated by Django 2.1.7 on 2019-03-06 19:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0011_auto_20190303_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('week', models.IntegerField()),
                ('sales', models.DecimalField(decimal_places=6, max_digits=20, validators=[django.core.validators.MinValueValidator(limit_value=1e-06, message='Sales records must be positive.')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(limit_value=0.01, message='Price per case in sales must be positive.')])),
                ('retrieval_time', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', related_query_name='sale', to='meals.Customer')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', related_query_name='sale', to='meals.Sku')),
            ],
            options={
                'ordering': ['year', 'week', 'sku__number', 'customer__pk'],
            },
        ),
    ]
