# Generated by Django 2.1.5 on 2019-02-06 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0011_auto_20190203_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='comment',
            field=models.CharField(blank=True, max_length=200, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='cost',
            field=models.FloatField(verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Ingr#'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='size',
            field=models.CharField(max_length=100, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.Vendor', verbose_name='Vendor'),
        ),
        migrations.AlterField(
            model_name='productline',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='comment',
            field=models.CharField(blank=True, max_length=200, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='unit_size',
            field=models.CharField(max_length=100, verbose_name='Unit size'),
        ),
        migrations.AlterField(
            model_name='skuingredient',
            name='ingredient_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.Ingredient', verbose_name='Ingr#'),
        ),
        migrations.AlterField(
            model_name='skuingredient',
            name='sku_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.Sku', verbose_name='SKU#'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='info',
            field=models.CharField(max_length=200, verbose_name='Info'),
        ),
    ]
